# Site settings
title: "MK Shim Resume"
description: "A resume in GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "MinKyoung Shim"
resume_title:                   "Data Scientist, Social Scientist, Would-be Full stack developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "chanlanv@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Seoul, KOREA"

resume_header_contact_info:     "Seoul, KOREA â€¢ chanlanv@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Thank you for visiting my resume page. There are my personal records.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
#resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
#resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
